version: "3.9"

services:
  redis:
    image: "redis:alpine"
    hostname: redis

  celery:
    build: .
    command: celery -A application:celery_app worker --concurrency=2
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

  flask:
    build: .
    command: python application.py
    ports:
      - "5000:5000"
    depends_on:
      - celery
    environment:
      REDIS_HOST: redis
